from typing import Protocol
from factorforge.strategy.domain.models import ObservedObject, TradingSnapshot, TargetOutbox


class TradingPort(Protocol):
    def snapshot(self, objects: list[ObservedObject]) -> TradingSnapshot: ...
    def prepare(self, obj: ObservedObject, item: TargetOutbox, snapshot: TradingSnapshot) -> dict: ...
    def deliver(self, obj: ObservedObject, item: TargetOutbox, snapshot: TradingSnapshot) -> dict: ...
    def simulate(self, scenario: dict) -> dict: ...
