"""The application accepts any verified adapter implementing these contracts."""
from contextlib import AbstractContextManager
from datetime import datetime
from typing import Protocol

from factorforge.trading.domain.models import Aggregate, Fill, InstrumentKey, MarketPoint, Order, RunKey


class ClockPort(Protocol):
    def now(self) -> datetime: ...


class StorePort(Protocol):
    environment: str
    def create(self, aggregate: Aggregate) -> None: ...
    def read(self, key: RunKey) -> Aggregate: ...
    def transaction(self, key: RunKey) -> AbstractContextManager[Aggregate]: ...


class BrokerPort(Protocol):
    environment: str
    def submit_order(self, run: Aggregate, order: Order) -> tuple[Order, list[Fill]]: ...
    def query_order(self, run: Aggregate, client_order_id: str) -> tuple[Order, list[Fill]]: ...
    def cancel_order(self, run: Aggregate, order: Order) -> tuple[Order, list[Fill]]: ...
    def get_capabilities(self) -> dict: ...
    def list_open_orders(self, run: Aggregate) -> list[Order]: ...
    def list_fills(self, run: Aggregate) -> list[Fill]: ...
    def get_positions(self, run: Aggregate) -> list: ...
    def submit_protection(self, run: Aggregate, protection): ...
    def query_protection(self, run: Aggregate, identifier: str): ...
    def cancel_protection(self, run: Aggregate, identifier: str): ...
    def get_account(self, run: Aggregate): ...
    def get_income(self, run: Aggregate) -> list: ...


class SimulationPort(Protocol):
    def advance_frame(self, run: Aggregate, key: InstrumentKey, liquidity, candle=None): ...


class MarketPort(Protocol):
    def instrument_specs(self) -> list: ...
    def latest_points(self, key: InstrumentKey) -> list[MarketPoint]: ...
    def candles(self, key: InstrumentKey, interval: str, start: datetime, end: datetime) -> list: ...
    def subscribe_updates(self, key: InstrumentKey): ...
