// Field constraints transcribed from frozen v2.1.0 models.
package domain

import "strconv"

func formatInteger(v int64) string { return strconv.FormatInt(v, 10) }
func bound(v int64) *int64         { return &v }

var modelRules = map[string][]fieldRule{
	"InstrumentKey":     {{name: "Venue", kind: "id"}, {name: "Product", kind: "enum", values: []string{"LINEAR_PERPETUAL"}}, {name: "InstrumentID", kind: "id"}},
	"RunKey":            {{name: "Environment", kind: "enum", values: []string{"SIM", "LIVE"}}, {name: "AccountID", kind: "id"}, {name: "RunID", kind: "id"}},
	"FxRate":            {{name: "Currency", kind: "id"}, {name: "Rate", kind: "number", gt: bound(0)}, {name: "SourceID", kind: "id"}},
	"StressScenario":    {{name: "ScenarioID", kind: "id"}, {name: "LossLimit", kind: "number", gt: bound(0)}, {name: "ExitCostRate", kind: "number", ge: bound(0), lt: bound(1)}},
	"OperationalPolicy": {{name: "MinDiskBytes", kind: "number", gt: bound(0)}, {name: "MaxClockSkewSeconds", kind: "number", gt: bound(0)}, {name: "MaxAuditRecords", kind: "number", gt: bound(0)}, {name: "MaxPendingCommands", kind: "number", gt: bound(0)}, {name: "MaxCommandAgeSeconds", kind: "number", gt: bound(0)}, {name: "LeaseSeconds", kind: "number", gt: bound(0)}},
	"ExternalFact":      {{name: "ExternalID", kind: "id"}, {name: "Kind", kind: "enum", values: []string{"MANUAL", "LIQUIDATION", "ADL", "SETTLEMENT", "INSTRUMENT_CHANGE"}}, {name: "AverageEntry", kind: "number", gt: bound(0)}, {name: "Currency", kind: "id"}, {name: "EvidenceRef", kind: "str", min: 1}, {name: "RuleVersion", kind: "id"}},
	"InstrumentSpec":    {{name: "Version", kind: "id"}, {name: "PriceTick", kind: "number", gt: bound(0)}, {name: "QuantityStep", kind: "number", gt: bound(0)}, {name: "ContractMultiplier", kind: "number", gt: bound(0)}, {name: "QuoteCurrency", kind: "id"}, {name: "SettlementCurrency", kind: "id"}, {name: "MinNotional", kind: "number", ge: bound(0)}, {name: "RiskGroup", kind: "id"}},
	"MarketPoint":       {{name: "SourceID", kind: "id"}, {name: "Kind", kind: "enum", values: []string{"BID", "ASK", "LAST", "MARK", "INDEX", "REFERENCE", "FX"}}, {name: "Value", kind: "number", gt: bound(0)}, {name: "Currency", kind: "id"}, {name: "Quality", kind: "enum", values: []string{"VALID", "STALE", "MISSING", "CONFLICT"}}, {name: "SpecVersion", kind: "id"}},
	"MarketTrade":       {{name: "ExternalID", kind: "id"}, {name: "SourceID", kind: "id"}, {name: "Price", kind: "number", gt: bound(0)}, {name: "Quantity", kind: "number", gt: bound(0)}, {name: "SpecVersion", kind: "id"}},
	"Candle":            {{name: "Interval", kind: "id"}, {name: "Open", kind: "number", gt: bound(0)}, {name: "High", kind: "number", gt: bound(0)}, {name: "Low", kind: "number", gt: bound(0)}, {name: "Close", kind: "number", gt: bound(0)}, {name: "Volume", kind: "number", ge: bound(0)}, {name: "SourceID", kind: "id"}, {name: "Revision", kind: "number", ge: bound(0)}},
	"LossGate":          {{name: "Mode", kind: "enum", values: []string{"OBSERVE", "ENFORCE"}}, {name: "Amount", kind: "number", gt: bound(0)}, {name: "Fraction", kind: "number", gt: bound(0), le: bound(1)}, {name: "Count", kind: "number", gt: bound(0)}},
	"AccountPolicy":     {{name: "Version", kind: "id"}, {name: "NotionalLimit", kind: "number", gt: bound(0)}, {name: "MarginLimit", kind: "number", gt: bound(0)}, {name: "TradeLossLimit", kind: "number", gt: bound(0)}, {name: "BreachAction", kind: "enum", values: []string{"KEEP_PROTECTION", "ORDERLY_REDUCE", "EXIT_WHEN_TRADABLE"}}, {name: "RecoveryPolicy", kind: "enum", values: []string{"MANUAL_RECONCILE"}}, {name: "MaxMarketAgeSeconds", kind: "number", gt: bound(0)}, {name: "NetNotionalLimit", kind: "number", gt: bound(0)}},
	"SimConfig":         {{name: "FeeRate", kind: "number", ge: bound(0), lt: bound(1)}, {name: "SlippageBps", kind: "number", ge: bound(0), lt: bound(10000)}, {name: "ParticipationRate", kind: "number", gt: bound(0), le: bound(1)}, {name: "LatencySeconds", kind: "number", ge: bound(0)}, {name: "MaintenanceMarginRate", kind: "number", gt: bound(0), lt: bound(1)}, {name: "OHLCRule", kind: "enum", values: []string{"CONSERVATIVE", "REJECT_AMBIGUOUS"}}, {name: "Leverage", kind: "number", ge: bound(1)}, {name: "LiquidationFeeRate", kind: "number", ge: bound(0), lt: bound(1)}, {name: "QueueAheadQuantity", kind: "number", ge: bound(0)}},
	"ProtectionPlan":    {{name: "TriggerKind", kind: "enum", values: []string{"MARK", "LAST"}}, {name: "TriggerPrice", kind: "number", gt: bound(0)}, {name: "CoveredQuantity", kind: "number", gt: bound(0)}, {name: "ExitOrderType", kind: "enum", values: []string{"MARKET"}}, {name: "MaxSlippageBps", kind: "number", ge: bound(0), lt: bound(10000)}, {name: "SpecVersion", kind: "id"}},
	"OrderRequest":      {{name: "OwnerID", kind: "id"}, {name: "Side", kind: "enum", values: []string{"BUY", "SELL"}}, {name: "OrderType", kind: "enum", values: []string{"MARKET", "LIMIT"}}, {name: "Quantity", kind: "number", gt: bound(0)}, {name: "LimitPrice", kind: "number", gt: bound(0)}, {name: "TimeInForce", kind: "enum", values: []string{"GTC", "IOC", "POST_ONLY"}}, {name: "PositionSide", kind: "enum", values: []string{"BOTH"}}, {name: "SpecVersion", kind: "id"}},
	"Command":           {{name: "SchemaVersion", kind: "enum", values: []string{"trading-2.0"}}, {name: "RequestID", kind: "id"}, {name: "IdempotencyKey", kind: "id"}, {name: "ExpectedVersion", kind: "number", ge: bound(0)}, {name: "Reason", kind: "str", min: 1, max: 500}},
	"Principal":         {{name: "PrincipalID", kind: "id"}, {name: "Environment", kind: "enum", values: []string{"SIM", "LIVE"}}, {name: "AccountID", kind: "id"}},
	"Order":             {{name: "OrderID", kind: "id"}, {name: "ClientOrderID", kind: "id"}, {name: "SourceProtectionID", kind: "id"}},
	"Fill":              {{name: "ExternalFillID", kind: "id"}, {name: "ExternalOrderID", kind: "id"}, {name: "Side", kind: "enum", values: []string{"BUY", "SELL"}}, {name: "Quantity", kind: "number", gt: bound(0)}, {name: "Price", kind: "number", gt: bound(0)}, {name: "Fee", kind: "number", ge: bound(0)}, {name: "FeeCurrency", kind: "id"}},
	"Position":          {{name: "OwnerID", kind: "id"}},
	"Protection":        {{name: "ProtectionID", kind: "id"}, {name: "OwnerID", kind: "id"}, {name: "ReplacesID", kind: "id"}, {name: "ExitOrderID", kind: "id"}},
	"Income":            {{name: "ExternalID", kind: "id"}, {name: "Kind", kind: "enum", values: []string{"FUNDING", "SPECIAL_FUNDING", "TRANSFER", "SETTLEMENT", "CORPORATE_ACTION"}}, {name: "Currency", kind: "id"}},
	"OutboxItem":        {{name: "CommandID", kind: "id"}, {name: "Kind", kind: "enum", values: []string{"SUBMIT", "CANCEL"}}, {name: "OrderID", kind: "id"}, {name: "PrincipalID", kind: "id"}, {name: "State", kind: "enum", values: []string{"PENDING", "DISPATCHING", "DONE", "UNKNOWN"}}, {name: "ClaimedBy", kind: "id"}},
	"Target":            {{name: "OwnerID", kind: "id"}, {name: "PolicyVersion", kind: "id"}, {name: "SpecVersion", kind: "id"}, {name: "SourceDecisionID", kind: "id"}},
	"Aggregate":         {{name: "ExecutionMode", kind: "enum", values: []string{"REPLAY", "SHADOW", "LIVE"}}, {name: "Currency", kind: "id"}, {name: "LeaseHolder", kind: "id"}},
}
